[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
port = 3000

[services.web]
numReplicas = 2

[[services.web.healthcheck]]
type = "http"
path = "/api/health"
interval = 30
timeout = 10 